package com.vivim.deepmine.mine.customblock;

public enum CUSTOM_BLOCK {
    DEFAULT_DIRT,
    DEFAULT_STONE,
    DEFAULT_COBBLESTONE,
    DEFAULT_SANDSTONE,
    DEFAULT_NETHERRACK,
    DEFAULT_ENDER_STONE,
    DEFAULT_OBSIDIAN,
    DEFAULT_ADAMANTIUM,
    DEFAULT_NETHERIUM,
    DEFAULT_TITAN,
    DEFAULT_SIENIT,

    DIRT_COMMON,
    DIRT_RARE,
    DIRT_EPIC,
    DIRT_LEGENDARY,

    STONE_COMMON,
    STONE_RARE,
    STONE_EPIC,
    STONE_LEGENDARY,

    COBBLESTONE_COMMON,
    COBBLESTONE_RARE,
    COBBLESTONE_EPIC,
    COBBLESTONE_LEGENDARY,

    SANDSTONE_COMMON,
    SANDSTONE_RARE,
    SANDSTONE_EPIC,
    SANDSTONE_LEGENDARY,

    NETHERRACK_COMMON,
    NETHERRACK_RARE,
    NETHERRACK_EPIC,
    NETHERRACK_LEGENDARY,

    ENDER_STONE_COMMON,
    ENDER_STONE_RARE,
    ENDER_STONE_EPIC,
    ENDER_STONE_LEGENDARY,

    ADAMANTIUM_COMMON,
    ADAMANTIUM_RARE,
    ADAMANTIUM_EPIC,
    ADAMANTIUM_LEGENDARY,

    NETHERIUM_COMMON,
    NETHERIUM_RARE,
    NETHERIUM_EPIC,
    NETHERIUM_LEGENDARY,

    TITAN_COMMON,
    TITAN_RARE,
    TITAN_EPIC,
    TITAN_LEGENDARY,

    SIENIT_COMMON,
    SIENIT_RARE,
    SIENIT_EPIC,
    SIENIT_LEGENDARY
}
